services:
  dropout-guard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - database
    environment:
      PG_HOST: database
      RABBIT_HOST: rabbitmq

  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: postgres:12.13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dropoutguard