logging:
  level:
    root: warn
spring:
  shell:
    command:
      completion:
        enabled: true
    interactive:
      enabled: true
    script:
        enabled: true
    context:
      close: true
  application:
    name: dropoutguard
  threads:
      virtual:
          enabled: true
  jackson:
      date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
      serialization:
          write-dates-as-timestamps: false
      deserialization:
        fail-on-unknown-properties: false
  datasource:
      url: jdbc:postgresql://${PG_HOST:localhost}:5432/dropoutguard
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  flyway:
      baseline-on-migrate: true
      locations: classpath:db/migration
  rabbitmq:
      host: ${RABBIT_HOST:localhost}


dropoutguard:
  infrastructure:
      knowledge-database:
          entrypoint:
              receive-status-update-listener:
                  queue-name: receive-knowledge-database-status-update-queue
                  concurrence: 5
              execute-update-listener:
                  queue-name: execute-knowledge-database-update-queue
                  concurrence: 5
              execute-update-job-listener:
                  queue-name: execute-knowledge-database-update-job-queue
                  concurrence: 5
          event:
              topic-name: KnowledgeDatabaseEventsTopic
      storage:
          local:
              root-path: storage