spring:
    application:
        name: dropoutguard
    threads:
        virtual:
            enabled: true
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        serialization:
            write-dates-as-timestamps: false
        deserialization:
          fail-on-unknown-properties: false


dropoutguard:
    infrastructure:
        knowledge-database:
            entrypoint:
                receive-status-update-listener:
                    queue-name: receive-knowledge-database-status-update-queue
                    concurrence: 5
            event:
                topic-name: KnowledgeDatabaseEventsTopic
        storage:
            local:
                root-path: src/test/java/br/ufs/dcomp/dropoutguard/integration