spring:
    application:
        name: dropoutguard
    threads:
        virtual:
            enabled: true
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        serialization:
            write-dates-as-timestamps: false
        deserialization:
          fail-on-unknown-properties: false


dropoutguard:
    infrastructure:
        knowledge-database:
            event:
                topic-name: KnowledgeDatabaseEventsTopic